services:
  app:
    image: authelia/authelia
    restart: unless-stopped
    secrets: ['JWT_SECRET', 'SESSION_SECRET', 'STORAGE_PASSWORD', 'STORAGE_ENCRYPTION_KEY']
    environment:
      PUID: 1000
      GUID: 1000
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/run/secrets/STORAGE_PASSWORD'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/STORAGE_ENCRYPTION_KEY'
    volumes:
      - '/etc/authelia/config:/config'

secrets:
  JWT_SECRET:
    environment: JWT_SECRET
  SESSION_SECRET:
    environment: SESSION_SECRET
  STORAGE_PASSWORD:
    environment: STORAGE_PASSWORD
  STORAGE_ENCRYPTION_KEY:
    environment: STORAGE_ENCRYPTION_KEY
